// <auto-generated />
using System;
using DhoobiGO.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DhoobiGO.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427180841_AddWashProofUrl")]
    partial class AddWashProofUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("integer");

                    b.Property<int?>("DhobiId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DhobiId");

                    b.HasIndex("OrderId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.DhobiService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DhobiId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DhobiId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("DhobiServices");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedEntityId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClothImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryProofUrl")
                        .HasColumnType("text");

                    b.Property<string>("DhobiDropProofUrl")
                        .HasColumnType("text");

                    b.Property<string>("DhobiPickupProofUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("InsuranceFee")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsInsured")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemsCount")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickupProofUrl")
                        .HasColumnType("text");

                    b.Property<string>("ProofImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("RiderFee")
                        .HasColumnType("numeric");

                    b.Property<int?>("RiderId")
                        .HasColumnType("integer");

                    b.Property<int?>("SelectedBidId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WashProofUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RiderId");

                    b.HasIndex("SelectedBidId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("DhobiId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int?>("RiderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DhobiId");

                    b.HasIndex("OrderId");

                    b.HasIndex("RiderId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.RiderBid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OfferedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OfferedFee")
                        .HasColumnType("numeric");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("RiderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("RiderId");

                    b.ToTable("RiderBids");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            BasePrice = 50m,
                            Category = "Cleaning",
                            CreatedAt = new DateTime(2026, 4, 27, 18, 8, 38, 347, DateTimeKind.Utc).AddTicks(5592),
                            Description = "Professional machine wash and tumble dry",
                            Icon = "water",
                            Name = "Washing"
                        },
                        new
                        {
                            Id = 102,
                            BasePrice = 20m,
                            Category = "Ironing",
                            CreatedAt = new DateTime(2026, 4, 27, 18, 8, 38, 347, DateTimeKind.Utc).AddTicks(8256),
                            Description = "Steam iron and hangers/folding",
                            Icon = "flash",
                            Name = "Ironing"
                        },
                        new
                        {
                            Id = 103,
                            BasePrice = 300m,
                            Category = "Special",
                            CreatedAt = new DateTime(2026, 4, 27, 18, 8, 38, 347, DateTimeKind.Utc).AddTicks(8263),
                            Description = "Delicate chemical cleaning for premium wear",
                            Icon = "star",
                            Name = "Dry Clean"
                        },
                        new
                        {
                            Id = 104,
                            BasePrice = 500m,
                            Category = "Cleaning",
                            CreatedAt = new DateTime(2026, 4, 27, 18, 8, 38, 347, DateTimeKind.Utc).AddTicks(8267),
                            Description = "Blankets, curtains and heavy fabrics",
                            Icon = "bed",
                            Name = "Heavy Duty"
                        },
                        new
                        {
                            Id = 105,
                            BasePrice = 100m,
                            Category = "Ironing",
                            CreatedAt = new DateTime(2026, 4, 27, 18, 8, 38, 347, DateTimeKind.Utc).AddTicks(8269),
                            Description = "Premium steam pressing for suits and dresses",
                            Icon = "shirt",
                            Name = "Steam Press"
                        });
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessLicenseUrl")
                        .HasColumnType("text");

                    b.Property<string>("CnicImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("CnicNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DataAnalyticsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("DhobiType")
                        .HasColumnType("integer");

                    b.Property<string>("DrivingLicenseUrl")
                        .HasColumnType("text");

                    b.Property<string>("ElectricityBillUrl")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailMarketingEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EquipmentImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("FatherName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLinkVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUpgradePending")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Landmark")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("LinkedDhobiId")
                        .HasColumnType("integer");

                    b.Property<bool>("LocationSharingEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("NtnNumber")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PoliceVerificationUrl")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<bool>("PushNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("ReferenceNumbers")
                        .HasColumnType("text");

                    b.Property<int?>("RequestedDhobiType")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.Property<int?>("RiderType")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SelfieWithIdUrl")
                        .HasColumnType("text");

                    b.Property<string>("ShopName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpgradeDocsUrl")
                        .HasColumnType("text");

                    b.Property<string>("VehicleImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("text");

                    b.Property<string>("VehicleRegistrationUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Platform HQ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataAnalyticsEnabled = true,
                            Email = "admin@dhoobi.com",
                            EmailMarketingEnabled = false,
                            FullName = "System Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            IsLinkVerified = false,
                            IsUpgradePending = false,
                            IsVerified = true,
                            Latitude = 0.0,
                            LocationSharingEnabled = true,
                            Longitude = 0.0,
                            PasswordHash = "$2a$11$Cx9So5ki0HB4olnZybRtU.Ke/SZUPes2ZyVVc9G2sNgelYbJo1XVW",
                            PhoneNumber = "0000000000",
                            PushNotificationsEnabled = true,
                            Rating = 5.0,
                            ReviewsCount = 0,
                            Role = 3
                        });
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Bid", b =>
                {
                    b.HasOne("DhoobiGO.Domain.Entities.User", "Dhobi")
                        .WithMany()
                        .HasForeignKey("DhobiId");

                    b.HasOne("DhoobiGO.Domain.Entities.Order", "Order")
                        .WithMany("Bids")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dhobi");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.DhobiService", b =>
                {
                    b.HasOne("DhoobiGO.Domain.Entities.User", "Dhobi")
                        .WithMany()
                        .HasForeignKey("DhobiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DhoobiGO.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dhobi");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Notification", b =>
                {
                    b.HasOne("DhoobiGO.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Order", b =>
                {
                    b.HasOne("DhoobiGO.Domain.Entities.User", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("DhoobiGO.Domain.Entities.User", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId");

                    b.HasOne("DhoobiGO.Domain.Entities.Bid", "SelectedBid")
                        .WithOne()
                        .HasForeignKey("DhoobiGO.Domain.Entities.Order", "SelectedBidId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Rider");

                    b.Navigation("SelectedBid");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Payment", b =>
                {
                    b.HasOne("DhoobiGO.Domain.Entities.Order", "Order")
                        .WithOne()
                        .HasForeignKey("DhoobiGO.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.PaymentMethod", b =>
                {
                    b.HasOne("DhoobiGO.Domain.Entities.Wallet", "Wallet")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Review", b =>
                {
                    b.HasOne("DhoobiGO.Domain.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("DhoobiGO.Domain.Entities.User", "Dhobi")
                        .WithMany("ReviewsAsDhobi")
                        .HasForeignKey("DhobiId");

                    b.HasOne("DhoobiGO.Domain.Entities.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DhoobiGO.Domain.Entities.User", "Rider")
                        .WithMany("ReviewsAsRider")
                        .HasForeignKey("RiderId");

                    b.Navigation("Customer");

                    b.Navigation("Dhobi");

                    b.Navigation("Order");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.RiderBid", b =>
                {
                    b.HasOne("DhoobiGO.Domain.Entities.Order", "Order")
                        .WithMany("RiderBids")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DhoobiGO.Domain.Entities.User", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.UserAddress", b =>
                {
                    b.HasOne("DhoobiGO.Domain.Entities.User", "User")
                        .WithMany("SavedAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("DhoobiGO.Domain.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("DhoobiGO.Domain.Entities.Wallet", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("DhoobiGO.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Order", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Reviews");

                    b.Navigation("RiderBids");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("ReviewsAsDhobi");

                    b.Navigation("ReviewsAsRider");

                    b.Navigation("SavedAddresses");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DhoobiGO.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("PaymentMethods");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
